require: rubocop-rspec

AllCops:
  Include:
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/*'
    - 'db/*'
    - 'config/*'
    - 'Guardfile'
    - 'Rakefile'
    - 'vendor/bundle/ruby/*'
  DisplayCopNames: true

RSpec/NamedSubject:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/FilePath:
  Enabled: false
Layout/LineLength:
  Max: 160
Metrics/MethodLength:
  Include: ['app/controllers/*']
  Max: 20
Metrics/AbcSize:
  Include: ['app/controllers/*']
  Max: 30
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  Enabled: false
  IgnoredMethods: ['describe', 'context', 'define', 'factory']

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: true
Gemspec/RequireMFA: # new in 1.23
  Enabled: false
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: false
Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: true
Lint/AmbiguousAssignment: # new in 1.7
  Enabled: true
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true
Lint/AmbiguousRange: # new in 1.19
  Enabled: true
Lint/DeprecatedConstants: # new in 1.8
  Enabled: true
Lint/DuplicateBranch: # new in 1.3
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: true
Lint/EmptyBlock: # new in 1.1
  Enabled: false
Lint/EmptyClass: # new in 1.3
  Enabled: true
Lint/EmptyInPattern: # new in 1.16
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: true
Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: true
Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: true
Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: true
Lint/RefinementImportMethods: # new in 1.27
  Enabled: true
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true
Lint/SymbolConversion: # new in 1.9
  Enabled: true
Lint/ToEnumArguments: # new in 1.1
  Enabled: true
Lint/TripleQuotes: # new in 1.9
  Enabled: true
Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: true
Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true
Naming/BlockForwarding: # new in 1.24
  Enabled: true
Security/CompoundHash: # new in 1.28
  Enabled: false
Security/IoMethods: # new in 1.22
  Enabled: true
Style/ArgumentsForwarding: # new in 1.1
  Enabled: true
Style/CollectionCompact: # new in 1.2
  Enabled: true
Style/DocumentDynamicEvalDefinition: # new in 1.1
  Enabled: true
Style/EndlessMethod: # new in 1.8
  Enabled: true
Style/EnvHome: # new in 1.29
  Enabled: true
Style/FetchEnvVar: # new in 1.28
  Enabled: true
Style/FileRead: # new in 1.24
  Enabled: true
Style/FileWrite: # new in 1.24
  Enabled: false
Style/HashConversion: # new in 1.10
  Enabled: false
Style/HashExcept: # new in 1.7
  Enabled: false
Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: false
Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: false
Style/MapToHash: # new in 1.24
  Enabled: false
Style/MultilineInPatternThen: # new in 1.16
  Enabled: false
Style/NegatedIfElseCondition: # new in 1.2
  Enabled: false
Style/NestedFileDirname: # new in 1.26
  Enabled: false
Style/NilLambda: # new in 1.3
  Enabled: false
Style/NumberedParameters: # new in 1.22
  Enabled: true
Style/NumberedParametersLimit: # new in 1.22
  Enabled: false
Style/ObjectThen: # new in 1.28
  Enabled: false
Style/OpenStructUse: # new in 1.23
  Enabled: false
Style/QuotedSymbols: # new in 1.16
  Enabled: false
Style/RedundantArgument: # new in 1.4
  Enabled: false
Style/RedundantInitialize: # new in 1.27
  Enabled: false
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: false
Style/SelectByRegexp: # new in 1.22
  Enabled: false
Style/StringChars: # new in 1.12
  Enabled: false
Style/SwapValues: # new in 1.1
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/CharacterLiteral:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Style/AndOr:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/Dir:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
RSpec/BeEq: # new in 2.9.0
  Enabled: false
RSpec/BeNil: # new in 2.9.0
  Enabled: false
RSpec/ChangeByZero: # new in 2.11.0
  Enabled: false
RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: false
RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: false
RSpec/SubjectDeclaration: # new in 2.5
  Enabled: false
RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: false
RSpec/FactoryBot/SyntaxMethods: # new in 2.7
  Enabled: false
RSpec/Rails/AvoidSetupHook: # new in 2.4
  Enabled: false
Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: false
Layout/LineContinuationSpacing: # new in 1.31
  Enabled: false
Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: false
Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: false
RSpec/Capybara/SpecificMatcher: # new in 2.12
  Enabled: false
RSpec/Rails/HaveHttpStatus: # new in 2.12
  Enabled: false
