default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  timeout: 5000
  port: 5432
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: fazebuk_development

test:
  <<: *default
  database: fazebuk_test

production:
  <<: *default
  database: fazebuk_production
  username: fazebuk
  password: <%= ENV['FAZEBUK_DATABASE_PASSWORD'] %>
