
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  timeout: 5000
  username: rvvergara
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fazebuk_development
test:
  <<: *default
  database: fazebuk_test
production:
  <<: *default
  database: fazebuk_production
  username: fazebuk
  password: <%= ENV['FAZEBUK_DATABASE_PASSWORD'] %>
