default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  timeout: 5000
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>

development:
  <<: *default
  database: fazebuk_development
test:
  <<: *default
  database: fazebuk_test
production:
  <<: *default
  database: fazebuk_production
  username: fazebuk
  password: <%= ENV['FAZEBUK_DATABASE_PASSWORD'] %>
